[2025-01-04T08:19:41.070+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-04T08:19:41.092+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-04T08:19:41.109+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-03T00:00:00+00:00 [queued]>
[2025-01-04T08:19:41.110+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-04T08:19:41.161+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): call_model_api_task> on 2025-01-03 00:00:00+00:00
[2025-01-04T08:19:41.166+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-01-04T08:19:41.169+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'model_prediction_dag', 'call_model_api_task', 'scheduled__2025-01-03T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/travel_prediction.py', '--cfg-path', '/tmp/tmp4221w0rf']
[2025-01-04T08:19:41.173+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask call_model_api_task
[2025-01-04T08:19:41.274+0000] {task_command.py:467} INFO - Running <TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-03T00:00:00+00:00 [running]> on host 303aeccca243
[2025-01-04T08:19:41.434+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='model_prediction_dag' AIRFLOW_CTX_TASK_ID='call_model_api_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-03T00:00:00+00:00'
[2025-01-04T08:19:41.435+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-04T08:19:41.526+0000] {logging_mixin.py:190} INFO - Prediction: {'prediction': [630.4428]}
[2025-01-04T08:19:41.527+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-04T08:19:41.540+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-04T08:19:41.541+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=model_prediction_dag, task_id=call_model_api_task, run_id=scheduled__2025-01-03T00:00:00+00:00, execution_date=20250103T000000, start_date=20250104T081941, end_date=20250104T081941
[2025-01-04T08:19:41.626+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-04T08:19:41.652+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-04T08:19:41.655+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
