[2025-01-22T02:31:23.047+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T02:31:23.071+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T02:31:23.088+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T02:31:23.089+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T02:31:23.145+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): call_model_api_task> on 2025-01-21 00:00:00+00:00
[2025-01-22T02:31:23.152+0000] {standard_task_runner.py:72} INFO - Started process 2676 to run task
[2025-01-22T02:31:23.155+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'model_prediction_dag', 'call_model_api_task', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/travel_prediction.py', '--cfg-path', '/tmp/tmpkrpb37kr']
[2025-01-22T02:31:23.157+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask call_model_api_task
[2025-01-22T02:31:23.270+0000] {task_command.py:467} INFO - Running <TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-21T00:00:00+00:00 [running]> on host 7f618819d11e
[2025-01-22T02:31:23.424+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='model_prediction_dag' AIRFLOW_CTX_TASK_ID='call_model_api_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-22T02:31:23.425+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T02:31:23.524+0000] {logging_mixin.py:190} INFO - Prediction: {'prediction': [630.4428]}
[2025-01-22T02:31:23.525+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-22T02:31:23.538+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T02:31:23.539+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=model_prediction_dag, task_id=call_model_api_task, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250122T023123, end_date=20250122T023123
[2025-01-22T02:31:23.611+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T02:31:23.632+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T02:31:23.635+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
