[2025-01-20T15:24:23.674+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T15:24:23.702+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T15:24:23.720+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-20T15:24:23.721+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-20T15:24:23.788+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): call_model_api_task> on 2025-01-19 00:00:00+00:00
[2025-01-20T15:24:23.801+0000] {standard_task_runner.py:72} INFO - Started process 1355 to run task
[2025-01-20T15:24:23.825+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'model_prediction_dag', 'call_model_api_task', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/travel_prediction.py', '--cfg-path', '/tmp/tmpp4qnu4mz']
[2025-01-20T15:24:23.841+0000] {standard_task_runner.py:105} INFO - Job 113: Subtask call_model_api_task
[2025-01-20T15:24:24.229+0000] {task_command.py:467} INFO - Running <TaskInstance: model_prediction_dag.call_model_api_task scheduled__2025-01-19T00:00:00+00:00 [running]> on host 7f618819d11e
[2025-01-20T15:24:24.642+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='model_prediction_dag' AIRFLOW_CTX_TASK_ID='call_model_api_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-20T15:24:24.645+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T15:24:25.226+0000] {logging_mixin.py:190} INFO - Prediction: {'prediction': [630.4428]}
[2025-01-20T15:24:25.230+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-20T15:24:25.269+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T15:24:25.271+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=model_prediction_dag, task_id=call_model_api_task, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250120T152423, end_date=20250120T152425
[2025-01-20T15:24:25.379+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T15:24:25.414+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T15:24:25.417+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
